metamor2018/Metamor

app/controllers/HomeController.scala, build.sbt, conf/application.conf
close #2
* ScalikeJdbcの設定をした
* javaJdbcを使っていたが、play-jdbcを使うように変更
* なし
* なし
=> [add] ScalikeJdbcの環境を追加

conf/evolutions/default/1.sql, conf/evolutions/default/10.sql, conf/evolutions/default/2.sql, conf/evolutions/default/3.sql, conf/evolutions/default/4.sql, conf/evolutions/default/5.sql, conf/evolutions/default/6.sql, conf/evolutions/default/7.sql, conf/evolutions/default/8.sql, conf/evolutions/default/9.sql
close #[issues番号]
* 全テーブルにcreated_at, deleted_atの追加
なし
なし
なし
=> [update] 全テーブルにcreated_at, deleted_atの追加

app/controllers/CreatorController.scala, app/models/repository/CreatorRepository.scala, app/models/repository/CreatorRepositoryImpl.scala, app/models/service/CreatorService.scala, build.sbt, conf/routes
close #9 
* クリエイターを作成出来るようにした
* play-circeの追加
なし
これでテストした 
curl http://localhost:9000/creator -X POST -H "Content-Type: application/json" -d '{"displayId": "huga", "name": "ほげ"}'
=> [add] クリエイターを作成できるようにした

app/controllers/WorldController.scala, app/models/entity/World.scala, app/models/repository/WorldRepository.scala, app/models/service/WorldService.scala, conf/routes, test/controllers/WorldControllerSpec.scala, test/mocks/ErrorWorldService.scala, test/mocks/MockWorldService.scala
close #21 
ワールド一覧取得機能のテストコード
・ワールドの情報が返ってくる
・ワールドの情報複数返ってくる
=> [add]ワールド一覧取得のテストコード

app/controllers/CharacterController.scala, app/models/entity/Character.scala, app/models/repository/CharacterRepository.scala, app/models/service/CharacterService.scala, conf/routes, test/controllers/CharacterControllerSpec.scala, test/mocks/ErrorCharacterService.scala, test/mocks/MockCharacterService.scala
close #23 
存在しているキャラクターを削除する機能
=> [add]キャラクター削除機能

app/controllers/WorldController.scala, app/forms/WorldEntryForm.scala, app/forms/validations/WorldValidations.scala, app/models/entity/World.scala, app/models/repository/CharacterRepository.scala, app/models/repository/WorldRepository.scala, app/models/service/CharacterService.scala, app/models/service/WorldService.scala, build.sbt, conf/evolutions/default/1.sql, conf/evolutions/default/10.sql, conf/evolutions/default/11.sql, conf/evolutions/default/2.sql, conf/evolutions/default/3.sql, conf/evolutions/default/4.sql, conf/evolutions/default/5.sql, conf/evolutions/default/6.sql, conf/evolutions/default/7.sql, conf/evolutions/default/8.sql, conf/evolutions/default/9.sql, conf/routes, test/controllers/ControllerSpecBase.scala, test/controllers/WorldControllerSpec.scala, test/mocks/ErrorCharacterService.scala, test/mocks/ErrorWorldService.scala, test/mocks/MockCharacterService.scala, test/mocks/MockWorldService.scala
close #25 
* ワールド参加機能
* testで必要になる要素を定義したControllerSpecBaseを作成
なし
なし
=> [add] ワールド参加機能追加

conf/application.conf
close #56 
* cors設定追加
* フロントからのリクエストを受け付けるようにした
* application.confに設定追加
なし
なし
=> [add] corsの設定追加

app/controllers/StatusController.scala, app/forms/StatusForm.scala, app/forms/validations/StatusValidations.scala, app/models/entity/Status.scala, app/models/repository/StatusRepository.scala, app/models/service/StatusService.scala, build.sbt, conf/db/fixtures/default/default.sql, conf/evolutions/default/8.sql, conf/routes, conf/test.conf, test/controllers/StatusControllerSpec.scala
close #76 
* 投稿作成機能の追加
* 投稿できようにした
* fixtureのやり方を知った
* 他のテストもやる必要があるけどmethodごとには無理そうかつ時間ないので今のままでいい
=> [add] 投稿作成機能の追加

app/controllers/WorldController.scala, app/models/entity/World.scala, app/models/repository/WorldRepository.scala, app/models/service/WorldService.scala, conf/db/fixtures/default/default.sql, conf/db/fixtures/default/entry.sql, conf/routes, test/controllers/StatusControllerSpec.scala, test/controllers/WorldControllerSpec.scala, test/mocks/ErrorWorldService.scala, test/mocks/MockWorldService.scala
close #94 
* ワールド取得機能
* 他のrepositoryで、worldidを取得するときにstringとして取得していたので修正
=> [add] ワールド取得機能追加

app/controllers/StatusController.scala, app/models/repository/StatusRepository.scala, app/models/service/StatusService.scala, conf/db/fixtures/default/default.sql, conf/db/fixtures/default/entry.sql, conf/db/fixtures/default/status.sql, conf/routes, test/controllers/StatusControllerSpec.scala
close #96
* 投稿一覧を取得
* GET    /character/:characterId/world/:worldId
* worldIdに紐づく投稿を取得
* ページングの機能を実装しないといけない
=> 投稿一覧表示機能の作成

app/controllers/CharacterController.scala, app/models/entity/Character.scala, app/models/repository/CharacterRepository.scala, app/models/service/CharacterService.scala, conf/routes, test/controllers/CharacterControllerSpec.scala, test/mocks/ErrorCharacterService.scala, test/mocks/MockCharacterService.scala
close #100
* /character/:id
上記URLにアクセスした際、
キャラクターの情報を取得するようにした
* CharacterControllerSpecをplayFixtureを用いたものにした
=> [add] キャラクターを1件取得する機能

app/controllers/WorldController.scala, app/forms/WorldEntryForm.scala, app/models/repository/WorldRepository.scala, app/models/service/WorldService.scala, conf/routes, test/controllers/WorldControllerSpec.scala, test/mocks/ErrorWorldService.scala, test/mocks/MockWorldService.scala
close #108 
* パラメータとjson両方でcreatorIdを取得する実装になっていたのでパラメータのみにした
* authActionになっていたのでActionにした
* エラーを適切なものに変更
* ServiceをEitherを返すものに変更
=> [bugfix] 創作者Idからワールド一覧を取得する機能

app/controllers/CharacterController.scala, app/models/repository/CharacterRepository.scala, app/models/service/CharacterService.scala, conf/db/fixtures/default/character.sql, conf/db/fixtures/default/entry.sql, conf/db/fixtures/default/status.sql, conf/db/fixtures/default/world.sql, conf/routes, conf/test.conf, test/controllers/CharacterControllerSpec.scala, test/controllers/StatusControllerSpec.scala, test/controllers/WorldControllerSpec.scala, test/mocks/ErrorCharacterService.scala, test/mocks/MockCharacterService.scala
close #107 
lineで何ページ目か受け取って１０人ずつ表示するようにした
あと何ページ目か表す変数lineでいいか
=> [update]キャラクターを10人ずつ受け取れるうようにgetByCreatorIdを変更

app/controllers/StatusController.scala, conf/routes, test/controllers/StatusControllerSpec.scala
close #114
* 投稿取得のURL変更
* characterIdを使用しない機能だったので、
URLを含まないものにした
=> [update] 投稿取得のURL変更

app/models/entity/Character.scala, app/models/entity/Status.scala, app/models/repository/CharacterRepository.scala, app/models/repository/StatusRepository.scala, app/models/service/StatusService.scala, test/controllers/StatusControllerSpec.scala, test/mocks/MockCharacterService.scala
close #117
* 投稿を取得する際、キャラクターと、創作者の情報も取得する
* キャラクターを取得する際に、創作者の情報も取得する機能も実装
* worldも取得するべき？
必要ではなさそうだったのでとりあえず実装せず
=> [update] 投稿を取得する際、キャラクターと、創作者の情報も取得する

app/controllers/CreatorController.scala, app/models/repository/CreatorRepository.scala, app/models/service/CreatorService.scala, conf/routes, test/controllers/CreatorControllerSpec.scala, test/mocks/ErrorCreatorService.scala, test/mocks/MockCreatorService.scala
=> [add] ログインしている創作者を取得する機能

app/controllers/WorldController.scala, app/forms/WorldForm.scala, app/forms/validations/WorldValidations.scala, app/models/repository/WorldRepository.scala, app/models/service/WorldService.scala, test/controllers/WorldControllerSpec.scala, test/mocks/ErrorWorldService.scala, test/mocks/MockWorldService.scala
close #52 
mockを使わないテストケースの追加
createで使用していたactionをauthActionに変更
=> [update]world作成機能の完成

app/controllers/CharacterController.scala, app/forms/CharacterForm.scala, app/forms/validations/CharacterValidations.scala, app/forms/validations/WorldValidations.scala, app/models/repository/CharacterRepository.scala, app/models/service/CharacterService.scala, test/controllers/CharacterControllerSpec.scala, test/mocks/ErrorCharacterService.scala, test/mocks/MockCharacterService.scala
close #124 
* キャラクターのidのバリデーションを追加
* 作成したキャラクターを返すようにした
=> [update] キャラクター作成後、作成したキャラクターを返すようにした

conf/routes
=> [update] キャラクターが参加しているワールド一覧の取得

app/controllers/StatusController.scala, app/models/repository/StatusRepository.scala, app/models/service/StatusService.scala, conf/routes, test/controllers/StatusControllerSpec.scala
close #134 
StatusControllerのgetByWorldIdのlineをstatusIdに変更
=> [update]lineをstatusIdに変更

app/controllers/StatusController.scala, app/models/repository/StatusRepository.scala, app/models/service/StatusService.scala, conf/routes, test/controllers/StatusControllerSpec.scala
close #[issues番号]
テスト
getStatusでSELECT COUNTしたかったがsqlじゃない部分がちょっと分からなかったため保留
=> [update]指定したstatusIdから最新の投稿までを全て取得する機能作成

app/controllers/AccountController.scala, app/models/repository/AccountRepository.scala, app/models/repository/CreatorRepository.scala, app/models/service/AccountService.scala, test/mocks/ErrorAccountService.scala, test/mocks/MockAccountService.scala
close #141
* 誰でログインしても同じ創作者を返してしまっていた
* sqlが、whereせずにfirstで取得していたので修正
=> [bugfix] 誰でログインしても同じ創作者を返していたのを修正

app/controllers/CharacterController.scala, app/models/repository/CharacterRepository.scala, app/models/service/CharacterService.scala, conf/db/fixtures/default/worldsEntries.sql, conf/routes, test/controllers/CharacterControllerSpec.scala, test/mocks/ErrorCharacterService.scala, test/mocks/MockCharacterService.scala
close #140 
ワールドと創作者で検索しキャラクターを取得する機能
=> [update]worldIdとcreatorIdからキャラクターを取得する機能

app/controllers/WorldController.scala
=> [update] ワールド作成後、ワールドidを返すようにした

app/models/repository/WorldRepository.scala
close #146 
ワールドを取得するとき降順で取得するように変更
* なにをどう変更したか
* ロジックがどういう手順で動くのか、
* DBからどういうクエリで何をとってそれに何を処理するのか、
* などなど、
* レビュワーにわかるように、技術的視線での変更概要説明
箇条書きで書く。できれば次のチケットを作る。
* あれこれを治す #xxxxxx
* あれそれを実装する #xxxxxx
* レビュワーに対する注意点 (ここはこういう風に思ったけどこういう風に実装した、ここはこうしようと思ったんだけどこういう悩みがありやめた、など注意点があれば)
* リリースに対する注意点 (その他)
=> ワールドを取得するとき降順で取得するように変更

app/controllers/CharacterController.scala, app/models/repository/CharacterRepository.scala, app/models/service/CharacterService.scala, conf/db/fixtures/default/character.sql, conf/db/fixtures/default/entry.sql, conf/routes, test/controllers/CharacterControllerSpec.scala, test/mocks/ErrorCharacterService.scala, test/mocks/MockCharacterService.scala
=> [add] 特定のワールドに参加していないキャラクターを取得
